version: '3.8'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: inventory_service
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - db:/var/lib/mysql
    networks:
      - inventory-service-net

  inventory-service-app:
    container_name: inventory-service-app
    build:
      context: .
      dockerfile: Dockerfile
    #restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    networks:
      - inventory-service-net
    depends_on:
      - mysqldb

networks:
  inventory-service-net:

volumes:
  db: